### ISSUE TITLE
manage /etc/aliases

### ISSUE THREAD

**Issue by hdep** [cirrax/puppet-postfix#1]
Hello,

I just try your module. So far it is working great.
Now I would like to manage the /etc/aliases in order to send root mail to a specific e-mail address. Is this possible with this plugin ? 

Regards,

**Comment by trefzer** [comment]
/etc/aliases is not managed by this module.
but you could use a map in postfix to achive the same.

**Comment by hdep** [comment]
Thank you for your feed back.
I did it with the following configuration using hiera

```
postfix::common_parameters:
smtp_generic_maps : hash:/etc/postfix/maps/hash_rewrite_local_sender
postfix::aliases: 
  hash_rewrite_local_sender:
    type: 'hash'
    contents:
      - 'root hugo@domain.com'
```
Maybe we can update the documentation in order to provide this example, or are you open for a PR in order to manage /etc/aliases ?

**Comment by hdep** [comment]
let me know if you want a PR for this. 
I close this ticket for now.

**Comment by trefzer** [comment]
Sorry for late answer ...
PR is of course always welcome !
